name: "Contrib Ingest (daily, tiny windows)"

on:
  schedule:
    - cron: "15 2 * * *"   # once per day at 02:15 UTC
  workflow_dispatch: {}

concurrency:
  group: contrib-ingest
  cancel-in-progress: true

permissions:
  contents: read

env:
  BASE_URL: https://www.blockbattle.org

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: "Check required secrets"
        run: |
          test -n "${{ secrets.CRON_SECRET }}" || { echo "CRON_SECRET missing in repo secrets"; exit 1; }

      - name: "Run tiny-window ingests (EVM-like: ARB, AVAX, ETH, OP, POL, BSC)"
        shell: bash
        run: |
          set -euo pipefail
          declare -A QS=(
            [eth]="sinceHours=0.25&maxBlocks=200&minConf=5"
            [arb]="sinceHours=0.25&maxBlocks=400&minConf=6"
            [avax]="sinceHours=0.20&maxBlocks=300&minConf=8"
            [op]="sinceHours=0.20&maxBlocks=400&minConf=6"
            [pol]="sinceHours=0.20&maxBlocks=500&minConf=20"
            [bsc]="sinceHours=0.25&maxBlocks=250&minConf=5"
          )
          for c in eth arb avax op pol bsc; do
            echo ">>> $c"
            if ! out=$(curl -sS --fail-with-body -X POST "$BASE_URL/api/ingest/contrib/$c?${QS[$c]}&debug=0" \
              -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" ); then
              echo "::warning:: $c ingest failed (HTTP) or route missing"; continue
            fi
            echo "$out" | jq -r '"ok=\(.ok) matched=\(.matched // 0) inserted=\(.inserted // 0) reason=\(.reason // "n/a")"'
            sleep 0.2
          done

      - name: "Run tiny-window ingests (UTXO: BTC, LTC, DOGE)"
        shell: bash
        run: |
          set -euo pipefail
          declare -A QS=(
            [btc]="sinceHours=0.25&maxBlocks=25&minConf=2"
            [ltc]="sinceHours=0.25&maxBlocks=50&minConf=3"
            [doge]="sinceHours=0.25&maxBlocks=50&minConf=6"
          )
          for c in btc ltc doge; do
            echo ">>> $c"
            curl -sS --fail-with-body -X POST "$BASE_URL/api/ingest/contrib/$c?${QS[$c]}&debug=0" \
              -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            | jq -r '"ok=\(.ok) matched=\(.matched // 0) inserted=\(.inserted // 0) reason=\(.reason // "n/a")"'
            sleep 0.2
          done

      - name: "Run tiny-window ingests (Ripple/Stellar: XRP, XLM)"
        shell: bash
        run: |
          set -euo pipefail
          declare -A QS=(
            [xrp]="sinceHours=0.25&maxLedgers=800&minConf=4"
            [xlm]="sinceHours=0.25&maxLedgers=800&minConf=4"
          )
          for c in xrp xlm; do
            echo ">>> $c"
            curl -sS --fail-with-body -X POST "$BASE_URL/api/ingest/contrib/$c?${QS[$c]}&debug=0" \
              -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            | jq -r '"ok=\(.ok) matched=\(.matched // 0) inserted=\(.inserted // 0) reason=\(.reason // "n/a")"'
            sleep 0.2
          done

      - name: "Run tiny-window ingests (Solana/Tron/Substrate/Cosmos: SOL, TRX, DOT, ATOM)"
        shell: bash
        run: |
          set -euo pipefail
          declare -A QS=(
            [sol]="sinceHours=0.05&maxSlots=300&minConf=64"
            [trx]="sinceHours=0.25&maxBlocks=300&minConf=19"
            [dot]="sinceHours=0.25&maxBlocks=300&minConf=3"
            [atom]="sinceHours=0.25&maxBlocks=300&minConf=3"
          )
          for c in sol trx dot atom; do
            echo ">>> $c"
            if ! out=$(curl -sS --fail-with-body -X POST "$BASE_URL/api/ingest/contrib/$c?${QS[$c]}&debug=0" \
              -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" ); then
              echo "::warning:: $c ingest failed (HTTP)"; continue
            fi
            echo "$out" | jq -r '"ok=\(.ok) matched=\(.matched // 0) inserted=\(.inserted // 0) reason=\(.reason // "n/a")"'
            sleep 0.2
          done
