name: Ingest ETH (hourly)

on:
  schedule:
    - cron: "10 * * * *"   # once per hour at minute 10 (UTC)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ingest-eth
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Call ETH height ingest
        run: |
          set -e
          echo "Calling https://www.blockbattle.org/api/ingest/eth ..."
          resp="$(curl -sSf -X POST "https://www.blockbattle.org/api/ingest/eth" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}")"
          echo "$resp"

