name: Ingest LTC (every 2 hours)

on:
  schedule:
    - cron: "4 */2 * * *"   # once per 2 hours at minute 04 (UTC)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ingest-ltc
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Call LTC height ingest
        run: |
          set -e
          echo "Calling https://www.blockbattle.org/api/ingest/ltc ..."
          resp="$(curl -sSf -X POST "https://www.blockbattle.org/api/ingest/ltc" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}")"
          echo "$resp"

