name: Ingest BTC (hourly)

on:
  schedule:
    - cron: "1 * * * *"   # once per hour at minute 01 (UTC)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ingest-btc
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Call BTC height ingest
        run: |
          set -e
          echo "Calling https://www.blockbattle.org/api/ingest/btc ..."
          resp="$(curl -sSf -X POST "https://www.blockbattle.org/api/ingest/btc" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}")"
          echo "$resp"

