name: Ingest SOL (every 2 hours)

on:
  schedule:
    - cron: "37 */2 * * *"   # once per 2 hours at minute 37 (UTC)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ingest-sol
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Call SOL height ingest
        run: |
          set -e
          echo "Calling https://www.blockbattle.org/api/ingest/sol ..."
          resp="$(curl -sSf -X POST "https://www.blockbattle.org/api/ingest/sol" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}")"
          echo "$resp"

