name: Ingest OP (hourly)

on:
  schedule:
    - cron: "13 * * * *"   # once per hour at minute 13 (UTC)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ingest-op
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Call OP height ingest
        run: |
          set -e
          echo "Calling https://www.blockbattle.org/api/ingest/op ..."
          resp="$(curl -sSf -X POST "https://www.blockbattle.org/api/ingest/op" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}")"
          echo "$resp"

