name: Ingest ATOM (every 15 min)
on:
  schedule:
    - cron: "*/15 * * * *"  # svakih 15 min (po potrebi prilagodi)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Call ingest ATOM
        env:
          BASE: https://www.blockbattle.org
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl -sS -X POST "$BASE/api/ingest/atom" \
            -H "x-cron-secret: $CRON_SECRET" \
            -H "Cache-Control: no-cache"

