name: Treemap Rollup (Daily)

on:
  schedule:
    - cron: "5 0 * * *" # 00:05 UTC dnevno
  workflow_dispatch: {}

jobs:
  rollup:
    runs-on: ubuntu-latest
    steps:
      - name: Call admin rollup endpoint
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          PROD_URL: https://www.blockbattle.org
        run: |
          set -euo pipefail
          curl -sS -X POST \
            -H "x-cron-secret: ${CRON_SECRET}" \
            "${PROD_URL}/api/admin/rollup-contributions-daily"

